services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./static:/usr/share/nginx/static:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
